# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablaghe_kol', models.CharField(max_length=20, null=True)),
                ('takhfif', models.CharField(max_length=20, null=True)),
                ('pardakht_avaliye', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(null=True)),
                ('time', models.IntegerField()),
                ('date', django_jalali.db.models.jDateField()),
            ],
        ),
        migrations.CreateModel(
            name='Register_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('imgfile', models.FileField(null=True, upload_to='img_profile/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('national_code', models.IntegerField(blank=True, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('born', models.CharField(max_length=50)),
                ('end_ejuction', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('school', models.CharField(max_length=50, null=True)),
                ('school_time', models.CharField(max_length=25, null=True)),
                ('father_ejuction', models.CharField(max_length=50, null=True)),
                ('father_work', models.CharField(max_length=50, null=True)),
                ('father_phone', models.CharField(max_length=50, null=True)),
                ('mother_ejuction', models.CharField(max_length=50, null=True)),
                ('mother_work', models.CharField(max_length=50, null=True)),
                ('mother_phone', models.IntegerField(blank=True, null=True)),
                ('physical_illness', models.CharField(max_length=50, null=True)),
                ('physical_illness_medicine', models.CharField(max_length=50, null=True)),
                ('mental_illness_medicine', models.CharField(max_length=50, null=True)),
                ('mental_illness', models.CharField(max_length=50, null=True)),
                ('detail', models.CharField(max_length=1000, null=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_code', models.IntegerField()),
                ('address', models.TextField()),
                ('mobile', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='register_student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(to='portal.Teacher'),
        ),
        migrations.AddField(
            model_name='financial',
            name='last_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Register_student'),
        ),
    ]
