# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Register_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('imgfile', models.FileField(blank=True, null=True, upload_to='img_profile/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('national_code', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('born', models.CharField(max_length=50)),
                ('end_ejuction', models.CharField(choices=[('1', 'دکتری'), ('2', 'فوق لیسانس'), ('3', 'لیسانس'), ('4', 'فوق دیپلم'), ('5', 'دیپلم'), ('6', 'یازدهم'), ('7', 'دهم'), ('8', 'هشتم'), ('9', 'هفتم'), ('10', 'ششم'), ('11', 'پنجم'), ('12', 'چهارم'), ('13', 'سوم'), ('14', 'دوم'), ('15', 'یکم'), ('16', 'پیش دبستانی'), ('17', 'عدم آغاز تحصیل')], max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(max_length=50, null=True)),
                ('school_time', models.CharField(max_length=25, null=True)),
                ('father_ejuction', models.CharField(choices=[('1', 'دکتری'), ('2', 'فوق لیسانس'), ('3', 'لیسانس'), ('4', 'فوق دیپلم'), ('5', 'دیپلم')], max_length=50, null=True)),
                ('father_work', models.CharField(max_length=50, null=True)),
                ('father_phone', models.CharField(max_length=50, null=True)),
                ('mother_ejuction', models.CharField(choices=[('1', 'دکتری'), ('2', 'فوق لیسانس'), ('3', 'لیسانس'), ('4', 'فوق دیپلم'), ('5', 'دیپلم'), ('6', 'زیر دیپلم')], max_length=50, null=True)),
                ('mother_work', models.CharField(max_length=50, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('physical_illness', models.CharField(max_length=50, null=True)),
                ('physical_illness_medicine', models.CharField(max_length=50, null=True)),
                ('mental_illness_medicine', models.CharField(max_length=50, null=True)),
                ('mental_illness', models.CharField(max_length=50, null=True)),
                ('detail', models.CharField(max_length=1000, null=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.FileField(blank=True, null=True, upload_to='img_teacher/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='register_student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Teacher'),
        ),
        migrations.AddField(
            model_name='financial',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Register_student'),
        ),
    ]
