# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='baghimande',
            field=models.CharField(default=[], max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial',
            name='daryafti',
            field=models.CharField(default=[], max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial',
            name='kole_shahrie',
            field=models.CharField(default=[], max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial',
            name='noe_takhfif',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='shahrie_bt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
