# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_number', models.IntegerField(blank=True)),
                ('sms_username', models.IntegerField(blank=True)),
                ('sms_password', models.IntegerField(blank=True)),
                ('father_message_sms', models.CharField(max_length=200)),
                ('mather_message_sms', models.CharField(max_length=200)),
                ('student_message_sms', models.CharField(max_length=200)),
                ('student_first_code', models.IntegerField()),
            ],
        ),
    ]
