# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170807_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='father_message_sms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='mother_message_sms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='sms_password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='sms_username',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='student_message_sms',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
