# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_register_student_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_student',
            name='imgfile',
            field=models.FileField(blank=True, null=True, upload_to='img_profile/'),
        ),
    ]
