# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170807_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='student_first_code',
            field=models.CharField(default=[], max_length=20),
            preserve_default=False,
        ),
    ]
