# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170613_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='imgfile',
            field=models.FileField(blank=True, null=True, upload_to='img_teacher/'),
        ),
        migrations.AlterField(
            model_name='register_student',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register_student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register_student',
            name='national_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register_student',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
