# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170719_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='sms_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
