# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170719_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='mather_message_sms',
            new_name='mother_message_sms',
        ),
    ]
