# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_setting_student_first_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='noe_takhfif',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
