# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170628_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
