# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20170712_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.CharField(default=[], max_length=100),
            preserve_default=False,
        ),
    ]
