# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20170719_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='student_first_code',
            field=models.CharField(max_length=20),
        ),
    ]
