# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20170719_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_student',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
