# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20170807_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Register_student'),
        ),
    ]
