# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20170731_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='mablaghe_kol',
        ),
        migrations.RemoveField(
            model_name='financial',
            name='pardakht_avaliye',
        ),
        migrations.RemoveField(
            model_name='financial',
            name='takhfif',
        ),
        migrations.AddField(
            model_name='financial',
            name='baghimande',
            field=models.CharField(default=[], max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial',
            name='daryafti',
            field=models.CharField(default=[], max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial',
            name='kole_shahrie',
            field=models.CharField(default=[1], max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial',
            name='m_takhfif',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='noe_takhfif',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='shahrie_bt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
