# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20170807_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_student',
            name='imgfile',
            field=models.FileField(blank=True, default='profile-icon.png', null=True, upload_to='img_profile/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='imgfile',
            field=models.FileField(blank=True, default='profile-icon.png', null=True, upload_to='img_teacher/'),
        ),
    ]
