# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20170807_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='sms_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
